### PR TITLE
Make a1op a simple box

### PR DESCRIPTION
**Pull request by cconcolato**
***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/147.html" title="Last updated on Apr 28, 2021, 5:04 PM UTC (e4515a6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/147/781b787...e4515a6.html" title="Last updated on Apr 28, 2021, 5:04 PM UTC (e4515a6)">Diff</a>

### CODE REVIEW

**Comment by cconcolato** [comment]
@tdaede

**Review by tdaede — APPROVED** [review]
Technically both the a1op and a1lx changes are backwards compatibility breaking, except that there are no released implementations yet.

**Review by wantehchang — APPROVED** [review]

**Comment by wantehchang** [comment]
Thomas: I agree that a1op breaks backward compatibility, but I think a1lx alone is backward compatible, because an older AVIF decoder should be able to decode a layered image and output the highest spatial layer.

**Comment by tdaede** [comment]
OK, as long as not decoding it exactly is OK then I think it counts.

**Comment by leo-barnes** [comment]
LGTM!

**Review by leo-barnes — APPROVED** [review]

**Pull request merged**
