### PR TITLE
Update Netflix AVIF Samples

### PR DESCRIPTION
**Pull request by joedrago**
The contents of `testFiles/Netflix/avif` didn't really reflect the most common CICP/subsampling/range combinations, and didn't have any associated PNGs or documentation to refer to. This PR attempts to address both. All of these files were generated with the latest `libavif` updates and should hopefully be useful to anyone implementing their own AVIF decoder or just trying to embed a pre-existing one.

Feel free to validate the files inside first and call out anything I might have missed.

### CODE REVIEW

**Comment by joedrago** [comment]
Shoot, some ICC profiles snuck into my encodings. I'll push a fix.

**Comment by joedrago** [comment]
There we go.

**Comment by joedrago** [comment]
@cconcolato I just updated them again to ensure they passed all ComplianceWarden tests. My latest update to libavif's master ensures that the av1C properties match the AV1 sequence headers inside of the AV1 payload, so these files are compliant now.

https://github.com/AOMediaCodec/libavif/commit/2172ed05169f08b20245221a7e95619a65884fd7

**Comment by cconcolato** [comment]
fyi @rbouqueau

**Review by cconcolato — APPROVED** [review]

**Pull request merged**
