### PR TITLE
add Netflix AVIF files generated with libavif

### PR DESCRIPTION
**Pull request by cconcolato**
Adds various files, in particular HDR content, encoded with different parameters (subsampling, bit depth, transfer function, bitrate) using libavif.

### CODE REVIEW

**Comment by joedrago** [comment]
Any movement on this? Who needs to review it?

**Comment by cconcolato** [comment]
I had requested a review from @aklemets but any independent review would do.

**Comment by aklemets** [comment]
Oh, my apologies. I totally missed this one. I can do the review today.

________________________________

**Comment by aklemets** [comment]
Joe, I think the .avif files are identical to the ones that were on Google drive before, and which I already reviewed. Right?
The .avifs files might be new to me. I am focusing on those now.

________________________________
From: Anders Klemets <aklemets@hotmail.com>
Sent: Monday, July 15, 2019 4:34:19 PM
To: AOMediaCodec/av1-avif; AOMediaCodec/av1-avif
Cc: Mention
Subject: RE: [AOMediaCodec/av1-avif] add Netflix AVIF files generated with libavif (#61)

Oh, my apologies. I totally missed this one. I can do the review today.

________________________________

**Comment by joedrago** [comment]
I can't speak to the Chimera ones (I think Cyril made them a long while ago), but this specific commit is just adding all of the cosmos images.

**Comment by aklemets** [comment]
Right, I realized now that the costmos files are the new ones and the .avifs files were just moved from a different folder. I spotted a problem with the Chimera .avifs file (it is missing the ‘pitm’ box) but it is not a new problem since the file was only moved.
I approved the PR.

________________________________

**Comment by cconcolato** [comment]
Thanks @aklemets I will provide a fix for the Chimera image sequence file.

**Pull request merged**
