### PR TITLE
Generating v1.1.0 version

### PR DESCRIPTION
**Pull request by cconcolato**
updating bikeshed file to Final Deliverable, generating snapshot and tweaking header to link various versions

***
<a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/pull/192.html" title="Last updated on May 5, 2022, 6:46 PM UTC (f50c58d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/AOMediaCodec/av1-avif/192/98ef5db...f50c58d.html" title="Last updated on May 5, 2022, 6:46 PM UTC (f50c58d)">Diff</a>

### CODE REVIEW

**Review by wantehchang — APPROVED** [review]
LGTM. Thank you, Cyril.

**Comment by leo-barnes** [comment]
LGTM as well.

Do we want to Copyright to be a range rather than a single year? We're internally told to use `2018-2022`, or `2018-2020, 2022` if we have gaps in changes. But maybe the copyright is really more linked with when it's published.
(I notice that the Copyright year has changed in the diff, but not in the bikeshed file, so I'm assuming it's auto-generated.)

**Review by leo-barnes — APPROVED** [review]

**Comment by cconcolato** [comment]
Yes, the Copyright is auto generated based on the date in the header. That's what I had been told to do some time ago. I'll double check.

**Review by wantehchang — APPROVED** [review]
Still LGTM. Thanks.

**Pull request merged**
