### PR TITLE
Update testFiles/Link-U/kimono*.avif files to make them spec compliant

### LINKED ISSUE #178: Invalid test files: transforms before `ImageSpatialExtentsProperty` (`ispe`)
Per HEIF (ISO/IEC 23008-12:2017) § 6.5.3.1:
> Every image item shall be associated with one property of this type, prior to the association of all transformative properties.

The following test files violate this property:
- [kimono.crop.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.avif)
- [kimono.mirror-horizontal.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.mirror-horizontal.avif)
- [kimono.mirror-vertical.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.mirror-vertical.avif)
- [kimono.mirror-vertical.rotate270.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.mirror-vertical.rotate270.avif)
- [kimono.mirror-vertical.rotate270.crop.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.mirror-vertical.rotate270.crop.avif)
- [kimono.rotate90.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.rotate90.avif)
- [kimono.rotate270.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Link-U/kimono.rotate270.avif)

### PR DESCRIPTION
**Pull request by leo-barnes**
Changes done:
1. Change order of item property associations to place ispe first
2. Add colr-nclx box with values 1,13,9,0 since this is what Sequence Header says
3. Strip out optional config OBUs from av1C

Fixes #178

### CODE REVIEW

**Comment by leo-barnes** [comment]
@ledyba-z 
Can't add you as a reviewer. Mind taking a look?

**Comment by ledyba-z** [comment]
@leo-barnes Thank you so much!
I will take a look in this weekend. Please wait a moment.
(I leave Link-U, and currently I am committing AVIF as a volunteer)

**Comment by leo-barnes** [comment]
Removed fixes for kimono*.crop.avif since those will get a more complete fix in #202

**Comment by leo-barnes** [comment]
@y-guyon @wantehchang 
Do either of you want to sanity check the files? If not I'll merge this PR.

**Comment by y-guyon** [comment]
I ran `avifdec` on all `kimono*.avif` and it only fails on `kimono.crop.avif` and `kimono.mirror-vertical.rotate270.crop.avif` with the error:

```
ERROR: Failed to parse image: BMFF parsing failed
Diagnostics:
 * [Strict] calculated crop X offset 543/2 is not an integer
```

which looks unrelated to this PR.

**Comment by leo-barnes** [comment]
> I ran `avifdec` on all `kimono*.avif` and it only fails on `kimono.crop.avif` and `kimono.mirror-vertical.rotate270.crop.avif` with the error:
> 
> ```
> ERROR: Failed to parse image: BMFF parsing failed
> Diagnostics:
>  * [Strict] calculated crop X offset 543/2 is not an integer
> ```
> 
> which looks unrelated to this PR.

Hmmm... I'll take a look at that, we ideally want all conformance files to actually make sense.

**Comment by baumanj** [comment]
FYI https://github.com/AOMediaCodec/av1-avif/issues/150 can be closed when those files get fixed up

**Comment by leo-barnes** [comment]
> > I ran `avifdec` on all `kimono*.avif` and it only fails on `kimono.crop.avif` and `kimono.mirror-vertical.rotate270.crop.avif` with the error:
> 
> Hmmm... I'll take a look at that, we ideally want all conformance files to actually make sense.

Ah. This got fixed with the other PR that handled the bad 'clap' cases.

**Pull request merged**
