### PR TITLE
Add pull_request to auto-publish.yml

### PR DESCRIPTION
**Pull request by y-guyon**

### CODE REVIEW

**Comment by wantehchang** [comment]
Yannis: I saw an "Approve and run" button and I clicked it.

**Comment by y-guyon** [comment]
Could someone merge this https://github.com/AOMediaCodec/av1-avif/pull/209 and https://github.com/AOMediaCodec/av1-avif/pull/205, or approve them and give me write access? Or should I regroup them in a single PR?

**Comment by cconcolato** [comment]
I'm not sure I understand why we need to add `pull_request` to `auto-publish.yml`? When I compare the settings of this repo with the AV1-ISOBMFF repo, they are identical and PR in AV1-ISOBMFF get preview and diff.

**Comment by y-guyon** [comment]
> I'm not sure I understand why we need to add `pull_request` to `auto-publish.yml`? When I compare the settings of this repo with the AV1-ISOBMFF repo, they are identical and PR in AV1-ISOBMFF get preview and diff.

It seems to replace the `Preview | Diff` feature by a standard GitHub workflow check. The check is more consistent with usual GitHub presubmit tests, but I do no longer see any link to the generated HTML, so this is worse.

**Pull request closed without merging**
